{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nomos-runner.fullname" . }}-grafana
  labels:
    app: {{ include "nomos-runner.name" . }}
    component: grafana
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.grafana.service.type "NodePort") .Values.grafana.service.nodePort }}
      nodePort: {{ .Values.grafana.service.nodePort }}
      {{- end }}
  selector:
    app: {{ include "nomos-runner.name" . }}
    component: grafana
{{- end }}
